import React, { FC } from 'react';

import { PageWrap } from '~/pages/styled';

const DashBoard: FC = () => (
  <PageWrap>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
  </PageWrap>
);

export default DashBoard;
