import React from 'react';
import { PageContent } from '../styled';

const DashBoard: React.FC = () => (
  <PageContent>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
    <p>DashBoard</p>
  </PageContent>
);

export default DashBoard;
